#!/bin/bash
#PBS -N prep-tgdt
#PBS -l select=1:ncpus=4:mem=64gb
#PBS -l walltime=08:00:00
#PBS -j oe

set -euo pipefail

cd /home/svu/e1553870/DSA5204-Group-Project
source /scratch/e1553870/venvs/dsa5204-laps/bin/activate

export OMP_NUM_THREADS=1
export OPENBLAS_NUM_THREADS=1
export MKL_NUM_THREADS=1

mkdir -p /scratch/e1553870/TGDT_data/logs

python ./scripts/prepare_tgdt_f30k.py \
  > /scratch/e1553870/TGDT_data/logs/prepare_tgdt_f30k-${PBS_JOBID}.out \
  2> /scratch/e1553870/TGDT_data/logs/prepare_tgdt_f30k-${PBS_JOBID}.err
